site_name: Fluxr Documentation
theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Components:
    - Tasks: components/tasks.md
    - Connectors: components/connectors.md
    - Tools: components/tools.md
    - Triggers: components/triggers.md
  - API Reference:
    - Flux: api/flux.md
    - Base Classes: api/base.md
    - Connectors: api/connectors.md
    - Tools: api/tools.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")